### ISSUE TITLE
[Feature] Cast ground mounts only under level 30

### ISSUE THREAD

**Issue by Paco-4272** [last-voice/mounty#3]
Would it be possible to block the mount cast from the ground kind when you haven't yet learned to fly?
Perhaps with an option to activate or not this restriction?

**Comment by last-voice** [comment]
This doesn't seem to be too complicated and I'd like to make your wish come true. But to be honest: I don't exactly understand what you are wishing for. ;) Please try to explain. 

ty!

#tlv

**Comment by last-voice** [comment]
This?

You want an option that makes Mounty cast the flying mounts even if you haven't learned to fly. 

__When doing magic: Ignore that I can't fly yet. On/Off__

**Comment by Paco-4272** [comment]
Hey :)
It's the opposite. I wish flying mounts weren't called if youdoesn't have the flying skill.

I'm building several characters and their level is low. They don't have the flying skill yet.
I configured Mouty with land mounts and flight mounts (for later), then I created a button via a Macro with "/mounty magic" to call the mount that corresponds to the situation. I'm also using the random call.
And in this case, it is the flying mounts that are cast. They can work, but they are too imposing I think.

Maybe this is a misuse on my part?

**Comment by last-voice** [comment]
So I understand, that it's only _/mounty random_ we are talking about and another chat command like _/mounty randomground_ would make your wish come true?

But: Why would you want a repair or water mount be cast, when you just want a ride. It's only ground mounts and show off mounts you want to be randomly chosen from, plus the 3 custom categories. Right?

So how about this:

_/mounty surprise_ will cast any mount out of fly, ground, show off and custom 1 2 3. But if in no flying area or unable to fly, it'll only cast legs and wheels. 

Good one?

**Comment by Paco-4272** [comment]
Sounds good 🙂

**Comment by last-voice** [comment]
Haha,

I started coding and it was weird, because Mounty #TLV should have already acted as you wished for. So I didn't need to add new functionality but fix a damn bug that I discovered.

With version 2.7.4. which I published a few minutes ago it should now be true magic again using Mounty #TLV. Please let me know, if it's like you want it to be: No flying mounts if you're still a walker. 

#tlv

**Comment by last-voice** [comment]
p.s.: So _/mounty surprise_ will do as _/mounty random_ did before and cast any(!) mount out of the journal. This has nothing to do with your issue here.

**Comment by Paco-4272** [comment]
Hi, it works for me.

Just so you know what I tested (I haven't done this professionally, but I think I've seen the main cases).
On 2 characters, one level 26, the other level 41 and with 2 commands "/mounty surprise" and "/mounty magic":
1. with Blizzard favorites, no Mounty favorites
2. no Blizzard favorites and no Mounty favorites
3. no Blizzard favorites and only Mounty terrestrials
4. no Blizzard favorites and only Mounty land mounts
5. no Blizzard favorites and only Mounty flying mounts
6. no favorites Blizzard and Mounty land and flying mounts
7. with Blizzard favorites, Mounty favorites of all kinds

As announced "/mounty surprise" does not take into account existing Blizzard or Mounty favorites and casts any owned mount.

And the "mounty magic" command works perfectly.
- if there is no Mounty land or flying mount, it works like "/mounty surprise" (even if there is a taxi or sea mount).
- if there are only land mounts or only flying ones, it will draw from them in all cases.
- if there are both, then the choice of the mount called will be made in the appropriate category according to the character's rider level.

I haven't tested in instance.

Thanks for the correction, it's cool, I will now be able to have random mounts, per character and no longer for the entire account.

Paco

**Comment by last-voice** [comment]
Thanks for all your time and the helpful feedback, Paco!

#tlv
